### ISSUE TITLE
infinite loop on bosh_exporter director/tasks/xxx

### ISSUE THREAD

**Issue by alexvasseur** [bosh-prometheus/bosh_exporter#11]
I had a situation that had like an infinite loop with bosh_exporter massively hitting the director
(This happened after the director was off for some time)

see screenshot
director cpu & worker
access log with >10 req/s and looping forever
I had to bosh stop prometheus/0 (IP x.y.z.185) to get rid of this

it is not clear to me why it has to go to all those tasks
![2017-07-16 23_54_22-jumpbox](https://user-images.githubusercontent.com/5575656/28326795-0868535a-6be2-11e7-8dd7-7c20519a64e4.png)
![2017-07-17 00_24_37-jumpbox](https://user-images.githubusercontent.com/5575656/28326797-0884b9dc-6be2-11e7-98c7-70e561ee292e.png)

**Comment by frodenas** [comment]
Are there any errors in the `bosh_exporter` logs?

Theoretically, the exporter closes the channel once the scrape reaches the timeout, so I'm unsure why there are so many tasks still running. Also, if the exporter is unable to get the deployments (ie the director is stopped), it should not trigger a task (as this only happens when it's able to get the deployments, and therefore, the vm's ids).

Something also weird that I see in your logs are the references to `/output?type=event`. The exporter is not requesting the `events`, so unsure where they came from.
