### ISSUE TITLE
Prometheus2 not found in template database 

### ISSUE THREAD

**Issue by fgraichen** [bosh-prometheus/bosh_exporter#19]
I am attempting to deploy Prometheus to director A with Cloud foundry running under director B.     When I run one of the tasks execute if fails saying Prometheus2 is not in the template database.   I assume this is director A PostgresSQL database.  Do I have an old version of the sql database and that is why this is not defined ?   How can I upgrade if that is the case.  This director is also running concourse.

**Comment by frodenas** [comment]
I guess you're refering to the [prometheus-boshrelease](https://github.com/bosh-prometheus/prometheus-boshrelease). If that's the case, this is because you're using the master branch manifest files, and you should be using one the releases branch. See more info at https://github.com/bosh-prometheus/prometheus-boshrelease/issues/184.
