### ISSUE TITLE
Getting deployment information causing load on the bosh director

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [bosh-prometheus/bosh_exporter#22]
Hi,

we observe some issues with the bosh exporter while getting deployment information from the bosh director in larger environments. It seems like this is caused by the fact that the exporter creates tasks for all deployments at once which causes the director to answer with 4xx and 5xx status codes on several requests.

This not only causes the exporter tasks to fail but also other deployment tasks triggered during that time. Is there any recommended way how to handle a bigger count of deployments combined with bosh exporter? Maybe reducing the scrape interval of the exporter can help because deployment data will normally not change that often.

Thanks for the help.

**Comment by frodenas** [comment]
Hi @benjaminguttmann-avtq,

Yes, one of the side-effects of this exporter is how it consumes the bosh information (there are more details at the [FAQ](https://github.com/bosh-prometheus/bosh_exporter/blob/master/FAQ.md#what-are-the-caveats-when-using-this-exporter)). I recommend increasing the `scrape_interval` based on the number of deployments/vms that your bosh director handles, because the [2m](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-bosh.yml#L44) default may be too agresive.

There's no workaround for this now. Some time ago I started looking for other scrape approaches (the [bosh_tsdb_exporter](https://github.com/bosh-prometheus/bosh_tsdb_exporter) is one of them, althought It does not provide the same functionality as this one), but I never finished my research.

**Comment by aegershman** [comment]
This is an ongoing investigation, but I'm seeing a ballooning number of tasks stored in `/var/vcap/store/director/tasks` correlated to exporter scrapes. I'm under the impression that every time either `bosh vms` or `bosh instances` are called, bosh should also initiate a cleanup of old tasks. 

My theory is that since the scrape requests are all coming in at exactly the same time, it appears to be overwhelming the cleanup process and causing a ballooning of `vm`-tasks and task logs on the director vm.

I'll try turning up the scrape interval, but I do wonder if the root of the problem is that the scrape requests are hitting the director for each deployment at almost _exactly_ the same time without jitter, and causing problems.

example of small snippet from `bosh tasks --recent --all`:

```
20654561  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  service-instance_15001beb-4db9-4227-bea5-e5b0fc0dd98e  retrieve vm-stats  -
20654560  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  p-rabbitmq-d31675f4e051a9411c20                        retrieve vm-stats  -
20654559  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  service-instance_31aa22dd-50af-4a44-a62a-a32364cafe7c  retrieve vm-stats  -
20654558  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  yugabyte_service_broker-6bf9a63a53399cbdd2dc           retrieve vm-stats  -
20654557  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  service-instance_ebf11fb7-241e-44ef-b9b3-4cb5b89ba0f9  retrieve vm-stats  -
20654556  done   Sun Jan 26 20:21:52 UTC 2020  Sun Jan 26 20:21:53 UTC 2020  bosh_exporter  concourse-apps                                         retrieve vm-stats  -
20654555  done   Sun Jan 26 20:21:49 UTC 2020  Sun Jan 26 20:21:49 UTC 2020  bosh_exporter  p_spring-cloud-services-b4f086e24529af4a55d5           retrieve vm-stats  -
20654554  done   Sun Jan 26 20:21:52 UTC 2020  Sun Jan 26 20:21:52 UTC 2020  bosh_exporter  service-instance_bdba0627-ee4f-46cd-a8ea-6ea2453866df  retrieve vm-stats  -
20654553  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  p-event-alerts-755f22806f19d1735230                    retrieve vm-stats  -
20654552  done   Sun Jan 26 20:21:53 UTC 2020  Sun Jan 26 20:21:53 UTC 2020  bosh_exporter  prometheus                                             retrieve vm-stats  -
20654551  done   Sun Jan 26 20:21:54 UTC 2020  Sun Jan 26 20:21:54 UTC 2020  bosh_exporter  service-instance_128517e7-6759-416a-8cbb-b388e00507ae  retrieve vm-stats  -
20654550  done   Sun Jan 26 20:21:52 UTC 2020  Sun Jan 26 20:21:53 UTC 2020  bosh_exporter  p-spring-cloud-services-ed246990d486488edc57           retrieve vm-stats  -
20654549  done   Sun Jan 26 20:21:49 UTC 2020  Sun Jan 26 20:21:49 UTC 2020  bosh_exporter  pivotal-mysql-6ce1a7ddcbd465a04fc4                     retrieve vm-stats  -
```

like I said, it's an ongoing investigation on my part, but the ballooning number of tasks is problematic due to the number of files (task logs) on the director vm
